Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")
install.packages("tidyverse")
install.packages("udunits2")
install.packages("plantecophys")
install.packages("photosynthesis")
devtools::install_github("ebimodeling/biocro")
devtools::install_github("PecanProject/pecan", subdir = "modules/photosynthesis", ref = "develop")
