install.packages("tidyverse")
install.packages("udunits2")
install.packages("plantecophys")
install.packages("photosynthesis")
devtools::install_github("ebimodeling/biocro")
#install.packages("rjags")
#devtools::install_github("PecanProject/pecan", subdir = "modules/photosynthesis", ref = "develop")
